spring.application.name=abgl-dms-api

# Database configuration
spring.datasource.url=jdbc:postgresql://codemaker.abytegroup.com:15432/alphadocs
spring.datasource.username=mtadmin
spring.datasource.password=ABGL46Strong
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Captcha settings
captcha.hmac-secret=change_me
captcha.ttl-minutes=5
captcha.cleanup-rate-ms=60000

# Logging
logging.level.root=INFO

# Captcha rate limiting
captcha.rate-limit.enabled=true
captcha.rate-limit.capacity=5
captcha.rate-limit.refill-tokens=5
captcha.rate-limit.refill-seconds=60
